substitutions:
  name: "m5stack-atom-echo"
  friendly_name: "M5Stack Atom Echo"
  wifi_ap_password: ""
  noise_key: "MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw"

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  project:
    name: m5stack.atom-echo
    version: "1.0"

esp32:
  board: m5stack-atom
  framework:
    type: arduino

logger:
api:
  encryption:
    key: "${noise_key}"

ota:

dashboard_import:
  package_import_url: github://esphome/media-players/m5stack-atom-echo.yaml@main

wifi:
  ap:
    password: "${wifi_ap_password}"

captive_portal:

improv_serial:

i2s_audio:
  i2s_lrclk_pin: GPIO33
  i2s_bclk_pin: GPIO19

microphone:
  - platform: i2s_audio
    id: echo_microphone
    i2s_din_pin: GPIO23

voice_assistant:
  microphone: echo_microphone

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: ${friendly_name} Button
    id: echo_button
    on_press:
      - voice_assistant.start:
    on_release:
      - voice_assistant.stop:
    on_click:
      - media_player.toggle: media_out

media_player:
  - platform: i2s_audio
    id: media_out
    name: ${friendly_name}
    dac_type: external
    i2s_dout_pin: GPIO22
    mode: mono

light:
  - platform: fastled_clockless
    id: led
    name: ${friendly_name}
    pin: GPIO27
    chipset: SK6812
    num_leds: 1
    rgb_order: grb
