packages:
  onju-voice: !include onju-voice.yaml

esphome:
  project:
    name: onju.voice-assistant
    version: dev

ota:
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    id: update_http_request
    name: Firmware
    source: https://firmware.esphome.io/media-player/onju-voice/manifest.json

http_request:
  verify_ssl: false

dashboard_import:
  package_import_url: github://esphome/media-players/onju-voice/onju-voice.yaml@main

improv_serial:
