packages:
  raspiaudio-muse-proto: !include raspiaudio-muse-proto.yaml

esphome:
  project:
    name: raspiaudio.muse-proto
    version: dev

ota:
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    id: update_http_request
    name: Firmware
    source: https://firmware.esphome.io/media-player/raspiaudio-muse-proto/manifest.json

http_request:
  verify_ssl: false

dashboard_import:
  package_import_url: github://esphome/media-players/raspiaudio/raspiaudio-muse-proto.yaml@main

improv_serial:
