packages:
  m5stack-atom-echo: !include m5stack-atom-echo.yaml

esphome:
  project:
    name: m5stack.atom-echo
    version: dev

ota:
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    id: update_http_request
    name: Firmware
    source: https://firmware.esphome.io/media-player/m5stack-atom-echo/manifest.json

http_request:
  verify_ssl: false

dashboard_import:
  package_import_url: github://esphome/media-players/m5stack/m5stack-atom-echo.yaml@main

improv_serial:
