name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-firmware:
    name: Build Firmware
    uses: esphome/workflows/.github/workflows/build.yml@2025.10.0
    with:
      files: |
        m5stack/m5stack-atom-echo.factory.yaml
        m5stack/m5stack-atom-speaker-kit.factory.yaml
        onju-voice/onju-voice.factory.yaml
        raspiaudio/raspiaudio-muse-luxe.factory.yaml
        raspiaudio/raspiaudio-muse-proto.factory.yaml
      esphome-version: 2025.9.3
      release-summary: ${{ github.event_name == 'release' && github.event.release.body || '' }}
      release-url: ${{ github.event_name == 'release' && github.event.release.html_url || '' }}
      release-version: ${{ github.event_name == 'release' && github.event.release.tag_name || '' }}

  upload-to-r2:
    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    name: Upload to R2
    needs:
      - build-firmware
    uses: esphome/workflows/.github/workflows/upload-to-r2.yml@2025.10.0
    with:
      directory: media-player
    secrets: inherit

  upload-to-release:
    name: Upload to Release
    if: github.event_name == 'release'
    uses: esphome/workflows/.github/workflows/upload-to-gh-release.yml@2025.10.0
    needs:
      - build-firmware
    with:
      version: ${{ github.event.release.tag_name }}

  promote-prod:
    name: Promote to Production
    if: github.event_name == 'release' && github.event.release.prerelease == false
    uses: esphome/workflows/.github/workflows/promote-r2.yml@2025.10.0
    needs:
      - upload-to-r2
    with:
      version: ${{ github.event.release.tag_name }}
      directory: media-player
      channel: production
    secrets: inherit
