name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-firmware:
    name: Build Firmware
    uses: esphome/workflows/.github/workflows/build.yml@main
    with:
      files: |
        m5stack/m5stack-atom-echo.factory.yaml
        m5stack/m5stack-atom-speaker-kit.factory.yaml
        onju-voice/onju-voice.factory.yaml
        raspiaudio/raspiaudio-muse-luxe.factory.yaml
        raspiaudio/raspiaudio-muse-proto.factory.yaml
      name: media-player
      esphome-version: 2024.7.3
      release-summary: ${{ github.event_name == 'release' && github.event.release.body || '' }}
      release-url: ${{ github.event_name == 'release' && github.event.release.url || '' }}
      upload: ${{ github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') }}
      release-version: ${{ github.event_name == 'release' && github.event.release.tag_name || '' }}
    secrets: inherit
