name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  publish-m5stack-atom-echo:
    name: Publish M5Stack Atom Echo
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: m5stack-atom-echo.yaml
      name: M5 Stack Atom Echo
      manifest_filename: m5stack-atom-echo-manifest.json
      clean: false
      esphome_version: beta

  publish-m5stack-atom-speaker-kit:
    name: Publish M5Stack Atom Speaker Kit
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: m5stack-atom-speaker-kit.yaml
      name: M5 Stack Atom Speaker Kit
      manifest_filename: m5stack-atom-speaker-kit-manifest.json
      clean: false
      esphome_version: beta

  publish-raspiaudio-muse-proto:
    name: Publish Raspiaudio Muse Proto
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: raspiaudio-muse-proto.yaml
      name: Raspiaudio Muse Proto
      manifest_filename: raspiaudio-muse-proto-manifest.json
      clean: false
      esphome_version: beta

  publish-raspiaudio-muse-luxe:
    name: Publish Raspiaudio Muse Luxe
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: raspiaudio-muse-luxe.yaml
      name: Raspiaudio Muse Luxe
      manifest_filename: raspiaudio-muse-luxe-manifest.json
      clean: false
      esphome_version: beta
