name: YAML lint

on:
  push:
    branches: [main]
    paths:
      - "**.yaml"
      - "**.yml"
  pull_request:
    paths:
      - "**.yaml"
      - "**.yml"

jobs:
  yamllint:
    name: 🧹 yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0.0
      - name: 🚀 Run yamllint
        run: yamllint --strict .
